@Library('github.com/releaseworks/jenkinslib') _

node {
  stage("LIST CLUSTERS") {
    withCredentials([[$class: 'UsernamePasswordMultiBinding',
    credentialsId: 'aws-key',
    usernameVariable: 'AWS_ACCESS_KEY_ID',
    passwordVariable: 'AWS_SECRET_ACCESS_KEY']]) {
        AWS("--region=us-east-2 --active --output=text --query='Clusters[*].[Id]' emr list-clusters")
    }
    echo "${AWS}"
  }
//   stage("TERMINATE CLUSTERS") {
//     withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'aws-key', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]) {
//         AWS("--region=us-east-2 --cluster-ids "" emr terminate-clusters")
//     }
//   }
}