pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh ("""
                    ls
                    emr/list-clusters.sh
                """)
            }
        }
    }
}